# Generated by Django 3.2 on 2022-01-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('subject', models.CharField(choices=[('general_question', 'GENERAL QUESTION'), ('update_my_order', 'UPDATE MY ORDER'), ('account_issue', 'ACCOUNT ISSUE'), ('offer_your_products', 'OFFER YOUR PRODUCTS')], default='general_question', max_length=100)),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Queries',
            },
        ),
    ]
