# Generated by Django 3.2 on 2022-01-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_review_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='title',
        ),
        migrations.AddField(
            model_name='productreview',
            name='nickname',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
