# Generated by Django 3.2 on 2022-01-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220128_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='nickname',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
    ]
