# Generated by Django 3.2 on 2022-01-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220129_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='nickname',
            field=models.CharField(default='Anonymous', max_length=30),
        ),
    ]
