# Generated by Django 3.2 on 2022-01-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_productreview_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
    ]
