# Generated by Django 3.2 on 2022-01-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_desc',
            new_name='comment_asc',
        ),
        migrations.RemoveField(
            model_name='post',
            name='magazine',
        ),
    ]
