# Generated by Django 3.2 on 2022-01-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_auto_20220127_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='intro',
            new_name='intro_text',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_asc',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
