# Generated by Django 3.2 on 2022-01-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_auto_20220127_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_asc',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_added',
            new_name='date_created',
        ),
    ]
