# Generated by Django 3.2 on 2022-01-28 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_auto_20220127_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='nickname',
        ),
    ]
