# Generated by Django 3.2 on 2022-01-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_rename_name_comment_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
    ]
