# Generated by Django 3.2 on 2022-01-29 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0006_alter_comment_nickname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
