# Generated by Django 3.2 on 2022-01-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created']},
        ),
    ]
