# Generated by Django 3.2 on 2022-01-17 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-date_added']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
