# Generated by Django 3.2 on 2022-01-18 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220117_2017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
