# Generated by Django 3.2 on 2022-01-19 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=254)),
                ('brand_frname', models.CharField(
                    blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_long',
        ),
        migrations.AddField(
            model_name='product',
            name='description_short',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='products.brand'),
        ),
    ]
